### ISSUE TITLE
Header com mix-blend

### ISSUE THREAD

**Issue by marcelluscaio** [CarolANikolic/010hout#1]
Carol, sugestão de implementação do mix-blend sem afetar os elementos do header:

.hero-header {
    width: 100%;
    height: 10%;
    position: relative;
    color: #000000;
    font-size: 2em;
    font-weight: 600;
}

.hero-header::after{
 content: "";
position: absolute;
top:0;
left:0;
width: 100%;
height: 100%;
background: #B27938;
mix-blend-mode: screen;   
}

**Comment by CarolANikolic** [comment]
Caio, 
Muito obrigada por apontar o problema e me ajudar a encontrar a solução. O problema com o logo foi resolvido.
Sua contribuição fez toda a diferença!
